### ISSUE TITLE
TST: Statespace: nans in VARMAX OIM standard errors.

### ISSUE THREAD

**Issue by ChadFulton** [statsmodels/statsmodels#2738]
See #2672 for examples. The `nan`s weren't there prior to numpy v1.10, but I don't think the new numpy is so much "to blame" as simply exposing the fragility of the standard errors here.

**Comment by ChadFulton** [comment]
In the short-term (i.e. this PR), I propose changing these tests to KnownFailure so that Statsmodels master can pass Travis again, and since there doesn't seem to be any simple fix at the moment.

Then I will create a new issue for Statespace standard errors generally and we can try to get some more robust calculations.

How does that sound?

**Comment by josef-pkt** [comment]
Is this the reason for the current failures?   Are these intentional nans or caused but difficult computations?
Is #2737 related to this?  We don't have the travisci results yet, so I didn't see whether it has any effect on the test results.

Adding known failure sound good, because then we would get TraviCI green again.
However, I'd like to know how `serious` the problem is. 
For example, we still have a few cases where we use linear algebra without checking for isfinite that might hang or even crash with some BLAS/LAPACK libraries, but doesn't with almost all of them or with the commonly used ones. (e.g. MKL does the isfinite check itself and raises instead).

**Comment by ChadFulton** [comment]
Are these fixed now with the work you and Skipper did last month?

**Comment by josef-pkt** [comment]
Current master runs without errors or failures. We don't know what caused the problem, but it was with the combination of default old (?) Ubuntu version and numpy 1.10.x.
Skipper updated the Ubuntu that is used and there is no problem with that. Also, there has been another numpy 1.10.x release.

It's still not clear if we were just hitting bugs outside of statsmodels, or if we have fragile code, or what the fragility in our code is.

I think we can ignore the problems for know, and wait to see whether they ever show up again.

**Comment by bashtage** [comment]
@ChadFulton Is this issue still relevant?

**Comment by ChadFulton** [comment]
I think we can close this, thanks!
