### ISSUE TITLE
BUG: Cannot import Pandas Timeseries

### ISSUE THREAD

**Issue by khider** [statsmodels/statsmodels#3752]
File "//anaconda/lib/python3.5/site-packages/statsmodels/base/data.py", line 8, in <module>
    from pandas import DataFrame, Series, TimeSeries, isnull

ImportError: cannot import name 'TimeSeries'

pandas version 0.20.2

**Comment by anonyXmous** [comment]
Hi, I am using anaconda and encountered the same error. I fixed it by running: conda install -c conda-forge statsmodels that I found in statmodels installation page.
Python: 3.5.3
Statsmodel: 0.8.0
Pandas: 0.20.2
Hope it will fix your issue as well. thanks.

**Comment by TomAugspurger** [comment]
@khider yes, pandas 0.20+ requires statsmodels 0.8 or newer.

**Comment by khider** [comment]
Any chance to make this available through pip as well?

**Comment by TomAugspurger** [comment]
@khider it should be there. https://pypi.org/project/statsmodels/#files

**Comment by fredcallaway** [comment]
I get the same problem with statsmodels 0.80 and pandas-0.20.2

**Comment by fredcallaway** [comment]
Bumping this. I just confirmed that the bug if fixed when installing directly from Github. Is it possible that this fix was made without a change to the version number?

**Comment by TomAugspurger** [comment]
Can you paste a full traceback? This was fixed in https://github.com/statsmodels/statsmodels/pull/3382

**Comment by fredcallaway** [comment]
My apologies. I installed it from pip in a virtual env and it worked fine. I'm at a loss why I could successfully update in my default environment from Github but not from PyPI... 🤔

**Comment by ClimbsRocks** [comment]
Just to verify, I also ran into this issue, and fixed it by upgrading all my installs (`pip install --upgrade statsmodels`, or in my case, `pip install --upgrade tsfresh`, which relies on statsmodels).

**Comment by tlsandbox** [comment]
after upgrading both packages, still cannot import timeseries properly..

**Comment by JeremieGauthier** [comment]
Yes, I've got the same problem. Even if I upgrade statsmodels with `pip install --upgrade statsmodels`, I am sttill having the same error `ImportError: cannot import name TimeSeries`.

**Comment by TomAugspurger** [comment]
Can you `pip uninstall statsmodels` and then post the output of `pip
install statsmodels`?

**Comment by JeremieGauthier** [comment]
With `sudo pip install pandas`, I've got 

> Collecting pandas
>   Using cached pandas-0.22.0-cp27-cp27mu-manylinux1_x86_64.whl
> Requirement already satisfied: pytz>=2011k in /usr/local/lib/python2.7/dist-packages (from pandas)
> Requirement already satisfied: numpy>=1.9.0 in /usr/local/lib/python2.7/dist-packages (from pandas)
> Requirement already satisfied: python-dateutil in /usr/local/lib/python2.7/dist-packages (from pandas)
> Requirement already satisfied: six>=1.5 in /usr/local/lib/python2.7/dist-packages (from python-dateutil->pandas)
> Installing collected packages: pandas
> Successfully installed pandas-0.22.0

and with `sudo pip install statsmodels`, I've got

> Collecting statsmodels
>   Using cached statsmodels-0.8.0-cp27-cp27mu-manylinux1_x86_64.whl
> Requirement already satisfied: scipy in /usr/local/lib/python2.7/dist-packages (from statsmodels)
> Requirement already satisfied: patsy in /usr/local/lib/python2.7/dist-packages (from statsmodels)
> Requirement already satisfied: pandas in /usr/local/lib/python2.7/dist-packages (from statsmodels)
> Requirement already satisfied: numpy>=1.8.2 in /usr/local/lib/python2.7/dist-packages (from scipy->statsmodels)
> Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (from patsy->statsmodels)
> Requirement already satisfied: pytz>=2011k in /usr/local/lib/python2.7/dist-packages (from pandas->statsmodels)
> Requirement already satisfied: python-dateutil in /usr/local/lib/python2.7/dist-packages (from pandas->statsmodels)
> Installing collected packages: statsmodels
> Successfully installed statsmodels-0.8.0

Be aware that I need to use python 2.7

**Comment by TomAugspurger** [comment]
And `import statsmodels`?

FYI, `sudo pip install` is best avoided if possible. Better to use virtualenvs.
