### ISSUE TITLE
BUG: DynamicFactor model - ValueError: object arrays are not supported

### ISSUE THREAD

**Issue by mboldin** [statsmodels/statsmodels#5512]
I get an error 'object arrays are not supported'  using the example code at
https://www.statsmodels.org/dev/examples/notebooks/generated/statespace_df
and also with my own code and data to run
mod = sm.tsa.DynamicFactor(endog, k_factors=1, factor_order=2, error_order=2)
initial_res = mod.fit(method='powell', disp=False)
res = mod.fit(initial_res.params, disp=False)

The error is
~/.local/lib/python3.6/site-packages/scipy/_lib/_util.py in _asarray_validated(a, check_finite, sparse_ok, objects_ok, mask_ok, as_inexact)
    240     if not objects_ok:
    241         if a.dtype is np.dtype('O'):
--> 242             raise ValueError('object arrays are not supported')
    243     if as_inexact:
    244         if not np.issubdtype(a.dtype, np.inexact):

ValueError: object arrays are not supported

I verified I am using statsmodels version 0.9.0
and the same data is accepted in other models

**Comment by ChadFulton** [comment]
Thanks for the bug report!

I can't immediately replicate this using the example notebook (which is running okay for me). Can you post the output you get when you run the following:

```python
import pandas as pd
import statsmodels.api as sm

print(sm.__version__)
print(pd.show_versions())
```

**Comment by mboldin** [comment]
Runing this code

mport os
import numpy as np
import pandas as pd

import statsmodels.api as sm

print('Statsmodels version', sm.version.version)

print('pd.show_versions()')
print(pd.show_versions())

I show

Statsmodels version 0.9.0
pd.show_versions()

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.5.final.0
python-bits: 64
OS: Linux
OS-release: 4.15.0-43-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8

pandas: 0.24.1
pytest: None
pip: 9.0.1
setuptools: 40.6.2
Cython: 0.29.3
numpy: 1.16.1
scipy: 1.2.1
pyarrow: None
xarray: None
IPython: 7.0.1
sphinx: None
patsy: 0.5.1
dateutil: 2.8.0
pytz: 2018.9
blosc: None
bottleneck: None
tables: 3.4.2
numexpr: 2.6.4
feather: None
matplotlib: 3.0.2
openpyxl: 2.5.9
xlrd: 1.1.0
xlwt: 1.3.0
xlsxwriter: None
lxml.etree: 4.2.5
bs4: 4.6.0
html5lib: 0.999999999
sqlalchemy: 1.1.11
pymysql: None
psycopg2: None
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: 0.7.0
gcsfs: None
None

**Comment by ChadFulton** [comment]
Thanks for posting that. Unfortunately, I still haven't been able to replicate a problem. If you can, please post a complete example (including data) that generates the exception.

**Comment by rebecca-palmer** [comment]
That looks like something I recently found in Debian (statsmodels 0.8.0, numpy 1.16.1, scipy 1.1.0, pandas 0.23.3); if so, it is [already fixed in master](https://github.com/statsmodels/statsmodels/pull/4911/commits/18dcceefbfed61b0d11ae5884a9f4cea82c2edb5#diff-05bedfca53e012a4a706c4fe4505c4c4).

**Comment by mboldin** [comment]
I ran on an Ubuntu 18.04 system and I suspect that numpy here cannot handle
the steps to create initial parameters.  I ported everything to a Windows
system and it ran fine.

**Comment by mboldin** [comment]
I was able estimate a simpler model by setting the start parameters.  I
suspect the problem was the default starting parameters produced a bad
covariance matrix that the numpy Linux version could not invert or
manipulate in some way. I think you just need a more elegant message for
bad starting value cases.

**Comment by ChadFulton** [comment]
Thanks for following up on this. I'm still not quite sure what's going on. I don't see any evidence so far that there's a problem with a covariance matrix. Is it possible that you could pass the entire except stack trace, so that we can see which call in the `DynamicFactor` class is raising the error?

**Comment by mboldin** [comment]
Here the full set  of errors

mod = sm.tsa.DynamicFactor(endog, k_factors=1, factor_order=2, error_order=2)
initial_res = mod.fit(method='powell', disp=False)
res = mod.fit(initial_res.params, disp=False)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-960a54f13f3c> in <module>
      4 
      5 mod = sm.tsa.DynamicFactor(endog, k_factors=1, factor_order=2, error_order=2)
----> 6 initial_res = mod.fit(method='powell', disp=False)
      7 res = mod.fit(initial_res.params, disp=False)

~/.local/lib/python3.6/site-packages/statsmodels/tsa/statespace/mlemodel.py in fit(self, start_params, transformed, cov_type, cov_kwds, method, maxiter, full_output, disp, callback, return_params, optim_score, optim_complex_step, optim_hessian, flags, **kwargs)
    449         # Unconstrain the starting parameters
    450         if transformed:
--> 451             start_params = self.untransform_params(np.array(start_params))
    452 
    453         # Maximum likelihood estimation

~/.local/lib/python3.6/site-packages/statsmodels/tsa/statespace/dynamic_factor.py in untransform_params(self, constrained)
    760             coefficient_matrices, variance = (
    761                 unconstrain_stationary_multivariate(
--> 762                     constrained_matrices, cov))
    763             unconstrained[self._params_factor_transition] = (
    764                 coefficient_matrices.ravel())

~/.local/lib/python3.6/site-packages/statsmodels/tsa/statespace/tools.py in unconstrain_stationary_multivariate(constrained, error_variance)
   1495     # (matrices with singular values less than one)
   1496     partial_autocorrelations = _compute_multivariate_pacf_from_coefficients(
-> 1497         constrained, error_variance, order, k_endog)
   1498 
   1499     # Step 2: convert from arbitrary matrices to those with singular values

~/.local/lib/python3.6/site-packages/statsmodels/tsa/statespace/tools.py in _compute_multivariate_pacf_from_coefficients(constrained, error_variance, order, k_endog)
   1434     autocovariances = [
   1435         autocovariance.T for autocovariance in
-> 1436         _acovf(constrained, error_variance, maxlag=order)]
   1437 
   1438     return _compute_multivariate_pacf_from_autocovariances(autocovariances)

~/.local/lib/python3.6/site-packages/statsmodels/tsa/statespace/tools.py in _compute_multivariate_acovf_from_coefficients(coefficients, error_variance, maxlag, forward_autocovariances)
   1171 
   1172     # Compute the unconditional variance of z_t: E z_t z_t'
-> 1173     stacked_cov = linalg.solve_discrete_lyapunov(companion, selected_variance)
   1174 
   1175     # The first (block) row of the variance of z_t gives the first p-1

~/.local/lib/python3.6/site-packages/scipy/linalg/_solvers.py in solve_discrete_lyapunov(a, q, method)
    316 
    317     if meth == 'direct':
--> 318         x = _solve_discrete_lyapunov_direct(a, q)
    319     elif meth == 'bilinear':
    320         x = _solve_discrete_lyapunov_bilinear(a, q)

~/.local/lib/python3.6/site-packages/scipy/linalg/_solvers.py in _solve_discrete_lyapunov_direct(a, q)
    214     lhs = kron(a, a.conj())
    215     lhs = np.eye(lhs.shape[0]) - lhs
--> 216     x = solve(lhs, q.flatten())
    217 
    218     return np.reshape(x, q.shape)

~/.local/lib/python3.6/site-packages/scipy/linalg/basic.py in solve(a, b, sym_pos, lower, overwrite_a, overwrite_b, debug, check_finite, assume_a, transposed)
    137     b_is_1D = False
    138 
--> 139     a1 = atleast_2d(_asarray_validated(a, check_finite=check_finite))
    140     b1 = atleast_1d(_asarray_validated(b, check_finite=check_finite))
    141     n = a1.shape[0]

~/.local/lib/python3.6/site-packages/scipy/_lib/_util.py in _asarray_validated(a, check_finite, sparse_ok, objects_ok, mask_ok, as_inexact)
    240     if not objects_ok:
    241         if a.dtype is np.dtype('O'):
--> 242             raise ValueError('object arrays are not supported')
    243     if as_inexact:
    244         if not np.issubdtype(a.dtype, np.inexact):

ValueError: object arrays are not supported

**Comment by ChadFulton** [comment]
Thanks very much! The underlying issue seems to be a change made between numpy v1.15 and numpy v1.16.

In 1.15 we have:

```python
> np.array([1., np.array([1.])])
array([1., 1.])
```

In 1.16 we have:

```python
> np.array([1., np.array([1.])])
array([1.0, array([1.])], dtype=object)
```

**Comment by ChadFulton** [comment]
To follow up with what I meant by that, in the `sm.tsa.statespace.tools. _compute_multivariate_acovf_from_coefficients` function we do the following:

```python
companion_matrix(
        [1] + [-np.squeeze(coefficients[i]) for i in range(order)]
    ).T
```

and then in `companion_matrix`, we construct: `np.asanyarray(polynomial)`, which used to (in numpy < 1.16) give us an array with dtype float, and now (in numpy >= 1.16) gives us that object array.

So what we need to do is fix `_compute_multivariate_acovf_from_coefficients` or `companion_matrix` or both, to accomodate the new numpy behavior.

**Comment by rebecca-palmer** [comment]
I thought that np.squeeze should already fix this (it was enough to fix the similar-looking error I'd seen in Debian's 0.8.0).  Has anyone seen this error in master?

**Comment by jbrockmendel** [comment]
@ChadFulton I can make the fix suggested above, but cannot reproduce the problem in the OP.  Can you suggest a valid test?

**Comment by rebecca-palmer** [comment]
What versions are you testing?  As noted above, I believe this is already fixed, by 18dcceef.

**Comment by bashtage** [comment]
Appears to be fixed in master, so closing.  Please reopen if this continues to be an issue.

**Comment by mboldin** [comment]
I verified the problem I found for DynamicFactor model fit()  
 ValueError: object arrays are not supported comp-tsa
Is fixed with STATSMODELS version 0.10rc2  (the same code fails with 0.9 but only appears to be a LINUX system case)
