### ISSUE TITLE
Theta forecaster: statsmodels vs sktime

### ISSUE THREAD

**Issue by jabudsc** [statsmodels/statsmodels#7075]
Hey guys, 
I have tried to compare the statsmodels implementation of the theta forecaster against the one from sktime. It turns out, that the fitted parameters (drift and alpha) are the same for both models but the one-step forecast is significantly different. This yields a much better performance of the sktime based model. Has anyone else observed such a behaviour?

**Comment by bashtage** [comment]
Can you provide an example that will show the difference?  The sm implementation is mostly based on Hyndaman and coauthor's reinterpretation of the model, rather than the original version.

**Comment by jabudsc** [comment]
Sure. Using the housing data you get the following results:
```python
from statsmodels.tsa.forecasting.theta import ThetaModel
from sktime.forecasting.theta import ThetaForecaster
import pandas_datareader as pdr

reader = pdr.fred.FredReader(["HOUST"], start="1980-01-01", end="2020-04-01")
data = reader.read()
housing = data.HOUST.reset_index(drop=True)

theta_sktime = ThetaForecaster(sp=12).fit(housing)
forecast_sktime = theta_sktime.predict(1)
alpha_sktime = theta_sktime.smoothing_level_
drift_sktime = theta_sktime.trend_ * (1 + (1 - (1 - alpha_sktime)) /alpha_sktime)

print('Parameters from sktime')
print('b0', drift_sktime)
print('alpha', alpha_sktime)
print('\nForecast from sktime')
print(forecast_sktime)
print('\n########################\n')

theta_sm = ThetaModel(housing,period=12).fit()
forecast_sm = theta_sm.forecast(1)

print('Parameters from statsmodels')
print(theta_sm.params)
print('\nForecast from statsmodels')
print(forecast_sm)
```
sktime does not return the drift parameter so I have calculated it using the formula from the source code.


My assumtion is, that this step is responsible for the difference.

https://github.com/statsmodels/statsmodels/blob/79a333ab3304d07baa077f6614b56a01d9957814/statsmodels/tsa/forecasting/theta.py#L453-L455

**Comment by mloning** [comment]
@jabudsc Thanks for raising the issue! From sktime's side, @big-o may be able to comment on this. As far as I remember, there are slightly different versions of Theta used in the M3 and M4 competition. 

We'd also be very happy to coordinate efforts to avoid code duplications. When we implemented the Theta method, statsmodels didn't have their own Theta yet, but I think in the long run we'd be happy to interface the statsmodels version.

**Comment by big-o** [comment]
Sktime's implementation is based on Hyndman & Billah 2003: Unmasking the Theta Method. If I understand correctly, the sm version is also based on the 2015 Fioruci et al paper so there may be some differences in the implementation. However, looking at plots of the forecasts across a wider horizon, it looks like there might be an "off-by-one" error in one of the implementations:

Input:

```python
import numpy as np
import pandas as pd
import pandas_datareader as pdr
from sktime.forecasting.model_selection import temporal_train_test_split
from sktime.forecasting.theta import ThetaForecaster
from sktime.utils.plotting import plot_series
from statsmodels.tsa.forecasting.theta import ThetaModel

reader = pdr.fred.FredReader(["HOUST"], start="1980-01-01", end="2020-04-01")
data = reader.read()
housing = data.HOUST.reset_index(drop=True)
sp = 12
alpha = 0.05
train, test = temporal_train_test_split(housing, test_size=0.1)

theta_sktime = ThetaForecaster(sp=sp).fit(train)
forecast_sktime, pred_ints_sktime = theta_sktime.predict(
    1 + np.arange(len(test)), return_pred_int=True, alpha=alpha
)
alpha_sktime = theta_sktime.smoothing_level_
drift_sktime = theta_sktime.trend_ * (1 + (1 - (1 - alpha_sktime)) / alpha_sktime)

print("Parameters from sktime")
print("b0", drift_sktime)
print("alpha", alpha_sktime)
print("\nForecast from sktime")
print(forecast_sktime[:3])
print("\n########################\n")

theta_sm = ThetaModel(train, period=sp).fit()
forecast_sm = theta_sm.forecast(len(test))
pred_ints_sm = theta_sm.prediction_intervals(len(test))

print("Parameters from statsmodels")
print(theta_sm.params)
print("\nForecast from statsmodels")
print(forecast_sm[:3])

fig, ax = plot_series(
    train[-len(test) // 2 :], test, forecast_sktime, forecast_sm, labels=["train", "test", "fcst_sktime", "fcst_sm"]
)

fig.set_size_inches(16, 9)
```

Output:

```
Parameters from sktime
b0 -1.0865165011842846
alpha 0.6091369366437318

Forecast from sktime
435    1131.632283
436    1127.716907
437    1122.898665
dtype: float64

########################

Parameters from statsmodels
b0      -1.086517
alpha    0.610906
dtype: float64

Forecast from statsmodels
435    1128.767894
436    1123.945663
437    1135.104959
Name: forecast, dtype: float64
```
![preds1](https://user-images.githubusercontent.com/1134151/95015155-61e67200-0643-11eb-8869-6208a6b40e1f.png)

From what I can see, when statsmodels prepares the horizon steps, it starts off with an `np.arange(1, steps + 1)`, but then it immediately subtracts one from all of these step values, which might be what's causing the shift:

https://github.com/statsmodels/statsmodels/blob/bb4d52cd69d1228e8fa9d0db96bba65616611918/statsmodels/tsa/forecasting/theta.py#L452

Is this expected behaviour?

We can also see that there's quite a big difference in the prediction intervals. This difference can be more pronounced at lower confidence levels:

```python
fig, ax = plot_series(
    train[-len(test) // 2 :], test, forecast_sktime, forecast_sm, labels=["train", "test", "fcst_sktime", "fcst_sm"]
)
ax.fill_between(
    ax.get_lines()[-2].get_xdata(),
    pred_ints_sktime["lower"],
    pred_ints_sktime["upper"],
    alpha=0.2,
    color=ax.get_lines()[-2].get_c(),
    label=f"{int(100*(1 - alpha))}% sktime prediction intervals",
)
ax.fill_between(
    ax.get_lines()[-1].get_xdata(),
    pred_ints_sm["lower"],
    pred_ints_sm["upper"],
    alpha=0.2,
    color=ax.get_lines()[-1].get_c(),
    label=f"{int(100*(1 - alpha))}% sm prediction intervals",
)
ax.legend()
fig.set_size_inches(16, 9)
```
![preds0](https://user-images.githubusercontent.com/1134151/95015188-89d5d580-0643-11eb-885d-d071ac8c43dd.png)

**Comment by bashtage** [comment]
> Sktime's implementation is based on Hyndman & Billah 2003: Unmasking the Theta Method. If I understand correctly, the sm version is also based on the 2015 Fioruci et al paper so there may be some differences in the implementation.

The version in statsmodels is based on both.  It allows for different values of theta which makes use of a simple relationship that comes out of the math in the 2003 article.

**Comment by bashtage** [comment]
> From what I can see, when statsmodels prepares the horizon steps, it starts off with an `np.arange(1, steps + 1)`, but then it immediately subtracts one from all of these step values, which might be what's causing the shift:
> 
> https://github.com/statsmodels/statsmodels/blob/bb4d52cd69d1228e8fa9d0db96bba65616611918/statsmodels/tsa/forecasting/theta.py#L452
> 
> Is this expected behaviour?

I think this is correct.  Here is a simple time series example

```
import numpy as np
from statsmodels.tsa.forecasting.theta import ThetaModel

rg = np.random.default_rng(0)
y = np.arange(100) + 0.0001*rg.standard_normal(100)

th = ThetaModel(y, period=12)
res = th.fit()
res.forecast_components(12)
```

produces

```
         trend        ses  seasonal
100   1.000109  98.999865  1.000001
101   2.000109  98.999865  1.000003
102   3.000109  98.999865  1.000003
103   4.000110  98.999865  0.999999
104   5.000110  98.999865  0.999999
105   6.000110  98.999865  0.999999
106   7.000111  98.999865  1.000001
107   8.000111  98.999865  0.999998
108   9.000111  98.999865  1.000000
109  10.000111  98.999865  1.000000
110  11.000112  98.999865  0.999999
111  12.000112  98.999865  0.999999
```

So that the 1-step ahead depends on the SES and the trend, which is 1 (+noise), 2 has trend 2(+noise), etc.

This also looks right.

```
res.prediction_intervals(10,alpha=2*stats.norm.cdf(-1)).to_numpy() - res.forecast(10).to_numpy()[:,None]
```
which returns 
```
array([[-1.00000027,  1.00000027],
       [-1.00000028,  1.00000028],
       [-1.00000028,  1.00000028],
       [-1.00000029,  1.00000029],
       [-1.0000003 ,  1.0000003 ],
       [-1.0000003 ,  1.0000003 ],
       [-1.00000031,  1.00000031],
       [-1.00000032,  1.00000032],
       [-1.00000032,  1.00000032],
       [-1.00000033,  1.00000033]])
```

This is an interval that is exactly +/- 1 sigma

The formula should be pretty simple since it comes from an ARIMA(p=0,d=1,q=1).

**Comment by big-o** [comment]
I'm still not sure what's going on, but using your simple example above I think it's clear that `sktime` is the one that's getting it wrong, both with the predictions and intervals. I'll raise an issue over in `sktime` to look into this further.

![simple_rng](https://user-images.githubusercontent.com/1134151/95651130-ede31880-0adf-11eb-8081-dfecbeabf25d.png)

**Comment by big-o** [comment]
> > Sktime's implementation is based on Hyndman & Billah 2003: Unmasking the Theta Method. If I understand correctly, the sm version is also based on the 2015 Fioruci et al paper so there may be some differences in the implementation.
> 
> The version in statsmodels is based on both. It allows for different values of theta which makes use of a simple relationship that comes out of the math in the 2003 article.

Just double checking - would the default options in the statsmodels implementation produce equivalent behaviour to the 2003 paper? The sktime implementation only uses the formulae directly referenced in the '03 article.

**Comment by jabudsc** [comment]
> I think it's clear that `sktime` is the one that's getting it wrong, both with the predictions and intervals.

I see the point. However, this doesn’t correspond to my experience. I’ve cross validated both implementations on an non-public time series and at least for this problem the `sktime` implementation performs much better. Of course, could be by chance but I am not convinced.

**Comment by big-o** [comment]
> > I think it's clear that `sktime` is the one that's getting it wrong, both with the predictions and intervals.
> 
> I see the point. However, this doesn’t correspond to my experience. I’ve cross validated both implementations on a non-public time series and at least for this problem the `sktime` implementation performs much better. Of course, could be by chance but I am not convinced.

Apologies - I updated my comment this morning after spotting a mistake but just realised I forgot to post the update. While the predictions for statsmodels look better in that case, the PIs strangely align with the sktime prediction more than the statsmodels one. I think some investigation may be needed into both implementations.

**Comment by bashtage** [comment]
There was definitely a bug in the prediction interval code. The forecast code looks right.  Bascially it should have a 50% damped trend, which looks right:

```
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

from statsmodels.tsa.forecasting.theta import ThetaModel

rg = np.random.default_rng(0)
y = np.arange(100) + rg.standard_normal(100)

th = ThetaModel(y, period=12, deseasonalize=False)
res = th.fit()
res.forecast_components(12)
h = 24
f = res.forecast(h)
pi = res.prediction_intervals(h)
plt.plot(np.arange(100 - 2 * h, 100), y[-2 * h :])
plt.plot(np.arange(100, 100 + h), f)
plt.fill_between(
    np.arange(100, 100 + h), pi.iloc[:, 0], pi.iloc[:, 1], alpha=0.4, zorder=-2
)
sns.despine()
plt.tight_layout(pad=1.0)
plt.show()

```

which produces

![image](https://user-images.githubusercontent.com/5585221/95664975-1bfa4400-0b44-11eb-8efb-6fa723b75b4d.png)

**Comment by bashtage** [comment]
I did some checking and these are very close now.
