### ISSUE TITLE
STLForecast shape bug

### ISSUE THREAD

**Issue by RGalkin** [statsmodels/statsmodels#7330]
Hello,

I'm trying to run this example: 
[https://www.statsmodels.org/stable/generated/statsmodels.tsa.forecasting.stl.STLForecast.html](https://www.statsmodels.org/stable/generated/statsmodels.tsa.forecasting.stl.STLForecast.html)

I keep getting the same error:
`ValueError: could not broadcast input array from shape (12,2) into shape (12)`

I also tried to run the STLForecast example from here:
[https://www.statsmodels.org/stable/examples/notebooks/generated/stl_decomposition.html?highlight=loess](https://www.statsmodels.org/stable/examples/notebooks/generated/stl_decomposition.html?highlight=loess)

and got the error:
`TypeError: __new__() got an unexpected keyword argument 'trend'`

statsmodels version: 0.12.1

**Comment by bashtage** [comment]
Can you post a complete example of what you are running?

The example works as expected for me.

```
import numpy as np
import pandas as pd
from statsmodels.tsa.api import STLForecast
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.datasets import macrodata
ds = macrodata.load_pandas()
data = np.log(ds.data.m1)
base_date = f"{int(ds.data.year[0])}-{3*int(ds.data.quarter[0])+1}-1"
data.index = pd.date_range(base_date, periods=data.shape[0], freq="QS")
stlf = STLForecast(data, ARIMA, model_kwargs={"order": (2, 1, 0)})
res = stlf.fit()
forecasts = res.forecast(12)
```

**Comment by RGalkin** [comment]
> Can you post a complete example of what you are running?
> 
> The example works as expected for me.
> 
> ```
> import numpy as np
> import pandas as pd
> from statsmodels.tsa.api import STLForecast
> from statsmodels.tsa.arima.model import ARIMA
> from statsmodels.datasets import macrodata
> ds = macrodata.load_pandas()
> data = np.log(ds.data.m1)
> base_date = f"{int(ds.data.year[0])}-{3*int(ds.data.quarter[0])+1}-1"
> data.index = pd.date_range(base_date, periods=data.shape[0], freq="QS")
> stlf = STLForecast(data, ARIMA, model_kwargs={"order": (2, 1, 0)})
> res = stlf.fit()
> forecasts = res.forecast(12)
> ```

This is the exact code I'm running.
Here a more detailed error:
`
  File "C:\Users\NUC-R2\Desktop\pythonml\models.py", line 757, in plot_STL
    forecasts = res.forecast(12)
  File "C:\Users\NUC-R2\anaconda3\Lib\site-packages\statsmodels\tsa\forecasting\stl.py", line 452, in forecast
    return forecast + self._seasonal_forecast(steps, index)
ValueError: could not broadcast input array from shape (12,2) into shape (12)`

**Comment by bashtage** [comment]
Upgrade to 0.12.2. I suspect the issue has been fixed between 0.12.1 and 0.12.2.

**Comment by RGalkin** [comment]
> Upgrade to 0.12.2. I suspect the issue has been fixed between 0.12.1 and 0.12.2.

I updated to version 0.12.2, I'm using the Anaconda.
![Screenshot 2021-02-18 141534](https://user-images.githubusercontent.com/46345584/108355860-08e33900-71f4-11eb-9c6d-7eb215c9483b.png)

I still got the same error.

**Comment by bashtage** [comment]
Something is wrong with your install.  Run

```
conda create -n sm122 -c conda-forge statsmodels==0.12.2 ipython -y
```

then open `ipython` and paste the code above in.  It works as expected.

**Comment by RGalkin** [comment]
The following code runs good in PowerShell but the error still occurs in anaconda.
I guess the problem is in Anaconda, I hoped that upgrading anaconda will solve it but I still get the same error.

**Comment by bashtage** [comment]
Did you run the commands I posted above? And did it work?

**Comment by RGalkin** [comment]
> Did you run the commands I posted above? And did it work?

Yes, it works in PowerShell, I printed out the results of the forecast and it works. 
I also run all the commands in the base environment in PowerShell, that also works. But when I run in Anaconda I still get the same error.

**Comment by bashtage** [comment]
This is telling you that your Anaconda installed version of statsmodels is
not 0.12.2.

**Comment by bashtage** [comment]
Closing as not a bug.
