### ISSUE TITLE
Misleading Constant returned by ARIMA Model

### ISSUE THREAD

**Issue by LordTarly** [statsmodels/statsmodels#7653]
#### Describe the bug

The constant returned by the ARIMA model is not the true intercept used, but seems to be (1-sum(AR params))*True Intercept

The intercept returned should be the same as an OLS model on the lagged time series.

#### Code Sample, a copy-pastable example if possible

```
import pandas as pd
import statsmodels.api as sm
from statsmodels.tsa.arima.model import ARIMA
import scipy as sp
import matplotlib.pyplot as plt

# Create Dummy Time Series

steps = 200

dummy = [1000, 1010]
sp.random.seed(12345)
errors = list(sp.random.normal(0, 15, steps))
for i in range(0, steps):
    dummy.append(dummy[-1] + 5 + 0.3 * (dummy[-1] - dummy[-2]) + errors[i])

plt.plot(dummy)

# Compare Models
diff_dummy = [j - i for i, j in zip(dummy[: -1], dummy[1:])]
arima = ARIMA(diff_dummy, order=(1, 0, 0), trend='c')
arima_fit = arima.fit()
print(arima_fit.summary())

y = diff_dummy[1:]
x = pd.DataFrame({'const': [1] * len(y), 'ar.L1': diff_dummy[:-1]})

ols = sm.OLS(y, x)
fit = ols.fit()
print(fit.summary())

# Fitted StatsModels

fitted = arima_fit.predict()
true_intercept = [fitted[i] - diff_dummy[i - 1] * arima_fit.arparams[0] for i in range(0, len(fitted) - 1)]
```

#### Expected Output

The constant returned should be the same as OLS

#### Output of ``import statsmodels.api as sm; sm.show_versions()``

```
INSTALLED VERSIONS
------------------
Python: 3.7.2.final.0
statsmodels
===========
Installed: 0.12.2
Required Dependencies
=====================
cython: Not installed
numpy: 1.21.2
scipy: 1.7.1
pandas: 1.3.2
    dateutil: 2.8.2
patsy: 0.5.1
Optional Dependencies
=====================
matplotlib: 3.4.3
    backend: TkAgg 
cvxopt: Not installed
joblib: Not installed
Developer Tools
================
IPython: Not installed
    jinja2: Not installed
sphinx: Not installed
    pygments: Not installed
pytest: Not installed
virtualenv: Not installed
```

**Comment by bashtage** [comment]
Please search through the issues and stackoverflow.  This has been addressed multiple times in the past few months.  (S)ARIMA(X) is technically OLS with ARMA errors, so that the model fit is y = x'beta + eps  where eps follows and ARMA process.  BEcause it is OLS with ARIMA errors, it will not match OLS even in large samples.  This is the correct behavior.

**Comment by bashtage** [comment]
For a more direct comparrison, you can use `AutoReg` which estimates AR models using OLS

```python
from statsmodels.tsa.api import AutoReg

AutoReg(diff_dummy,1).fit().summary()
```


```
                            AutoReg Model Results                             
==============================================================================
Dep. Variable:                      y   No. Observations:                  201
Model:                     AutoReg(1)   Log Likelihood                -824.409
Method:               Conditional MLE   S.D. of innovations             14.926
Date:                Thu, 19 Aug 2021   AIC                           1654.817
Time:                        09:20:52   BIC                           1664.712
Sample:                             1   HQIC                          1658.822
                                  201                                         
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          4.2327      1.151      3.679      0.000       1.978       6.488
y.L1           0.4062      0.065      6.282      0.000       0.279       0.533
                                    Roots                                    
=============================================================================
                  Real          Imaginary           Modulus         Frequency
-----------------------------------------------------------------------------
AR.1            2.4621           +0.0000j            2.4621            0.0000
-----------------------------------------------------------------------------
```

**Comment by bashtage** [comment]
Closing because there is no action for us.  If this isn't clear, and the other issues (closed) don't clarify, please continue to use this thread.

**Comment by LordTarly** [comment]
I couldn't find related questions, could you link specific threads on stackoverflow addressing this?

I still don't understand the output of ARIMA, why is the constant equal to Intercept * (1-AR[1])?
If you try predicting the next value out of sample using the parameters provided, you'd try: Y(t+1) = const + AR[1] * Y(t), and you'd be wrong, since what the model is really doing is Y(t+1) = const*(1-AR[1]) + AR[1]*Y(t).

So why not return the first term directly?

In _get_predict_out_of_sample in arima_model.py, line 342 for example, you define mu as const * (1-arparams.sum()), and then use this as constant.

**Comment by bashtage** [comment]
See this notebook for a more detailed explanation:

https://github.com/statsmodels/statsmodels/blob/1805933f0648af4b64cc06fa189975912993b2a3/examples/notebooks/statespace_sarimax_faq.ipynb

**Comment by LordTarly** [comment]
Appreciate the follow-up and understand now the different representations - it may be helpful to clarify though how ARIMA and SARIMAX are defined and what the coefficients returned are.

I would think users would commonly expect an ARIMA model to be defined as you define SARIMAX, rather than as it currently is - as you show, fitting a SARIMAX(1,0,0) without exogenous variables is a different definition than ARIMA(1,0,0), while I would have thought SARIMAX to be an expansion of ARIMA and thus to be returning consistent estimates and fitting consistent equations for something that ultimately defaults to an AR(1).

If I've missed the distinction in the documentation, that's on me then.

**Comment by bashtage** [comment]
It is in the notes, but a bit buried.

_This model incorporates both exogenous regressors and trend components through “regression with ARIMA errors”._
